### PR TITLE
internally proposed change around funargs

### PR DESCRIPTION
**Pull request by waddella**
@gmbecker please have a look at the proposed change, the internal team has found this to solve some issues we get in `tern` (internal software) when preparing the switch to R 4.1.

### CODE REVIEW

**Comment by waddella** [comment]
sorry I forgot to disable the circleci hooks, you can merge regardless

**Comment by gmbecker** [comment]
@waddella I would still like more context around this change. What is the error? Because again, I develop rtables in 4.1.0 and things are passing/working/etc for me, so the actual problem is unlikely (not impossible, but unlikely) to be the change between 3.6.x and 4.1.0

**Comment by waddella** [comment]
@gmbecker this is the error I get (in an internal package) without the change

image

I have sent you instructions per email on how to replicate the error.

**Comment by waddella** [comment]
see #226

**Pull request closed without merging**
