### PR TITLE
Correcting typos.

### LINKED ISSUE #364: Read analyze documentation
Carefully read this documentation:

https://roche.github.io/rtables/reference/analyze.html

If you have improvement/clarification suggestions create a PR.

### PR DESCRIPTION
**Pull request by ayogasekaram**
closes #364

### CODE REVIEW

**Review by gmbecker — APPROVED** [review]

**Comment by Melkiades** [comment]
We should merge this

**Review by Melkiades — APPROVED** [review]

**Comment by Melkiades** [comment]
@ayogasekaram should we merge this?

**Comment by ayogasekaram** [comment]
@Melkiades Yes I believe it should be okay but I don't have access to merge. I can pull again and make sure there are still no issues.

**Comment by Melkiades** [comment]
@gmbecker

**Pull request merged**
