### PR TITLE
Add function links in vignettes

### LINKED ISSUE #383: Vignettes fix URLs to function documentation
so that function references are linked to the documentation (as in the `dplyr` vignettes)

### PR DESCRIPTION
**Pull request by edelarua**
Added `()` to function mentions in all vignettes to create links to function documentation. Also added a few hyperlinks to repo sites.

Closes #383

### CODE REVIEW

**Review by Melkiades — APPROVED** [review]
Lgtm! Well done 👍

**Comment by shajoezhu** [comment]
Hi @gmbecker , can we merge this PR? thanks

**Review by gmbecker — CHANGES_REQUESTED** [review]

**Review by gmbecker — APPROVED** [review]

**Comment by shajoezhu** [comment]
Hi @gmbecker thanks a lot for approving this PR, can we merge this already? Thanks

**Comment by gmbecker** [comment]
@edelarua please resolve conflicts with the other PR and in the future don't prepare multiple PRs that touch the same documentation or functions simultaneously. These could have just been the same PR.

**Review by gmbecker — APPROVED** [review]

**Pull request merged**
